server:
  port: 9000
#  servlet:
#    context-path: /auth-server

spring:
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect